/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    Copy: typeof import('./src/components/Search - Copy.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    InfoTrackBanner: typeof import('./src/components/InfoTrackBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}
